#!/bin/bash
#SBATCH --job-name=cutandrun
#SBATCH --output=/hpc/shared/onco_janssen/dhaynessimmons/projects/fly_acetylation_damage/logs/cutandrun-%j.out
#SBATCH --error=/hpc/shared/onco_janssen/dhaynessimmons/projects/fly_acetylation_damage/logs/cutandrun-%j.err
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=100G
#SBATCH --mail-type=all
#SBATCH --mail-user=d.j.haynes-simmons@umcutrecht.nl

# Load the workflow configuration
source /hpc/shared/onco_janssen/dhaynessimmons/projects/fly_acetylation_damage/scripts/config/nf_env_config.sh

nextflow run nf-core/cutandrun \
  --input /hpc/shared/onco_janssen/dhaynessimmons/projects/fly_acetylation_damage/data/SEND-bulkChIC-UMC-JAN-003-008-2/cut_run_samplesheet.csv \
  --outdir /hpc/shared/onco_janssen/dhaynessimmons/projects/fly_acetylation_damage/results/drosophila_alignments \
  --genome BDGP6 \
  --use_control false \
  --seacr_peak_threshold 0.05 \
  --seacr_norm non --seacr_stringent relaxed \
  --peakcaller seacr \
  --normalisation_mode CPM \
  --replicate_threshold 2 \
  --spikein_bowtie2 null \
  --spikein_fasta null \
  -profile singularity
